[package]
name = "vt-sdk-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "vt_sdk_core"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
image = { version = "0.24", default-features = false, features = ["png", "jpeg", "bmp", "gif"] }
