name: build-ios-xcframework

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Add iOS targets
        run: rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios

      - name: Build FFI for iOS
        run: |
          set -euxo pipefail
          cargo build -p vt-sdk-ffi --release --target aarch64-apple-ios
          cargo build -p vt-sdk-ffi --release --target aarch64-apple-ios-sim
          cargo build -p vt-sdk-ffi --release --target x86_64-apple-ios

      - name: Create XCFramework
        run: |
          set -euxo pipefail
          mkdir -p dist
          lipo -create -output dist/libvt_sdk_ffi_sim.a \
            target/aarch64-apple-ios-sim/release/libvt_sdk_ffi.a \
            target/x86_64-apple-ios/release/libvt_sdk_ffi.a
          xcodebuild -create-xcframework \
            -library target/aarch64-apple-ios/release/libvt_sdk_ffi.a -headers ffi/include \
            -library dist/libvt_sdk_ffi_sim.a -headers ffi/include \
            -output dist/VTSDK.xcframework
          (cd dist && zip -r VTSDK.xcframework.zip VTSDK.xcframework)

      - name: Build iOS sample app (simulator, no codesign)
        run: |
          set -euxo pipefail
          xcodebuild \
            -project ios-demo/VTSDKDemo.xcodeproj \
            -scheme VTSDKDemo \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath build-output \
            build

      - name: Upload sample app artifact
        uses: actions/upload-artifact@v4
        with:
          name: VTSDKDemo.app
          path: build-output/Build/Products/Debug-iphonesimulator/VTSDKDemo.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VTSDK.xcframework
          path: |
            dist/VTSDK.xcframework
            dist/VTSDK.xcframework.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: VTSDK.xcframework
          path: dist

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/VTSDK.xcframework.zip
