name: build-android-so

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Add Android targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android

      - name: Configure Cargo for NDK linkers
        run: |
          set -euxo pipefail
          NDK=${ANDROID_NDK_LATEST_HOME:-$ANDROID_NDK_HOME}
          mkdir -p .cargo
          cat > .cargo/config.toml <<EOF
          [target.aarch64-linux-android]
          linker = "${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"
          ar = "${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"

          [target.armv7-linux-androideabi]
          linker = "${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang"
          ar = "${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"

          [target.x86_64-linux-android]
          linker = "${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang"
          ar = "${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
          EOF

      - name: Build FFI .so for ABIs
        run: |
          set -euxo pipefail
          cargo build -p vt-sdk-ffi --release --target aarch64-linux-android
          cargo build -p vt-sdk-ffi --release --target armv7-linux-androideabi
          cargo build -p vt-sdk-ffi --release --target x86_64-linux-android
          mkdir -p dist/android/arm64-v8a dist/android/armeabi-v7a dist/android/x86_64
          cp target/aarch64-linux-android/release/libvt_sdk_ffi.so dist/android/arm64-v8a/
          cp target/armv7-linux-androideabi/release/libvt_sdk_ffi.so dist/android/armeabi-v7a/
          cp target/x86_64-linux-android/release/libvt_sdk_ffi.so dist/android/x86_64/
          # Header (generated by build.rs)
          cp ffi/include/vt_sdk.h dist/
          (cd dist && zip -r android-libs.zip android vt_sdk.h)

      - name: Upload artifacts (.so + header)
        uses: actions/upload-artifact@v4
        with:
          name: android-libs
          path: |
            dist/android
            dist/vt_sdk.h
            dist/android-libs.zip

