name: macos-tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Run cargo test (workspace)
        run: cargo test --workspace --all-features --verbose

